### ISSUE TITLE
Error when creating reactor recipes

### ISSUE THREAD

**Issue by Water-Moon** [Prunoideae/Heat-And-Climate-Tweaker#1]
When using `ReactorPrimer.setCatalyst()`, a `NoClassDefFoundError` is thrown, and the recipe change is unsuccessful.
The error stack trace in the `crafttweaker.log` is
```
[INITIALIZATION][CLIENT][ERROR] [crafttweaker]: Error executing {[0:crafttweaker]: AS+HeatAndClimate.zs}: scala/actors/threadpool/Arrays
java.lang.NoClassDefFoundError: scala/actors/threadpool/Arrays
	at com.ib.hactweaker.Zenscripts.ReactorPrimer.setCatalyst(ReactorPrimer.java:73)
	at AS+HeatAndClimate.__script__(AS+HeatAndClimate.zs:9)
	at __ZenMain__.run(AS+HeatAndClimate)
	at crafttweaker.runtime.CrTTweaker.loadScript(CrTTweaker.java:225)
	at crafttweaker.runtime.CrTTweaker.loadScript(CrTTweaker.java:105)
	at crafttweaker.mc1120.events.CommonEventHandler.registerRecipes(CommonEventHandler.java:69)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_908_CommonEventHandler_registerRecipes_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857)
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:629)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:742)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3931)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: scala.actors.threadpool.Arrays
	at java.net.URLClassLoader.findClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 23 more
```

The recipe itself is
```
var NewRecipe = mods.hac.Reactor.newRecipe();
NewRecipe.addInput(<dcs_climate:dcs_gem:2>);
NewRecipe.setOutput(<techreborn:smalldust:45>);
NewRecipe.addHeat(-2);
NewRecipe.addHeat(-1);
NewRecipe.addHeat(0);
NewRecipe.setFluidI1(<liquid:glowstone>*200);
NewRecipe.setFluidO1(<liquid:astralsorcery.liquidstarlight> * 2000);
NewRecipe.setCatalyst([<dcs_climate:dcs_catalyst:1>]);
NewRecipe.ignite();
```

**Comment by Water-Moon** [comment]
Personally, I think this error is caused by incorrect `import` statement in `ReactorPrimer.java`.
The line (line 11)
`import scala.actors.threadpool.Arrays;`
might have caused the error. (Most likely due to auto import of IDE)

Consider changing it to:
`import java.util.Arrays;`
This should fix the problem.

**Comment by Prunoideae** [comment]
Oops, looks like I didn't check the import.
